services:
  backend:
    build: ./backend
    environment:
      - OSRM_URL=${OSRM_URL:-http://router.project-osrm.org}
    restart: unless-stopped
    network_mode: host

  frontend:
    build: ./frontend
    network_mode: host
    restart: unless-stopped
    environment:
      - DOCQA_PASSWORD=${APP_PASSWORD}
      - DOCQA_USER=${APP_USER:-admin}
